### ISSUE TITLE
Ntfy support(for the F-Droid variant of Amethyst)

### ISSUE THREAD

**Issue by KotlinGeekDev** [vitorpamplona/amethyst-push-notif-server#1]
This issue is here mostly to track the status of the implementation of UnifiedPush/Ntfy support with/until the PR that will come along.

**Comment by KotlinGeekDev** [comment]
Please @vitorpamplona  I have two questions :sweat_smile:  :
1. Please how are the tokens for pubkeys obtained? ( I don't really understand the <-app.post('/register', .. -> line. Is it talking to the Heroku instance?)
2.  Will it be necessary to differentiate Firebase-subscribed pubkeys from ntfy-subscribed pubkeys?(Since the notify function is making Firebase calls)

**Comment by vitorpamplona** [comment]
`/register` is called when the token changes in the app or on onResume to update the server if the server has lost the token. 

> Firebase-subscribed pubkeys from ntfy-subscribed pubkeys

Probably. We might just use a different server for F-droid. Then we would fork this one, delete the Firebase stuff and add the nfty ones.

**Comment by KotlinGeekDev** [comment]
> `/register` is called when the token changes in the app or on onResume to update the server if the server has lost the token.

Please how are the tokens generated? I have not seen anything in the code(or I may have missed it :sweat_smile: )

**Comment by vitorpamplona** [comment]
Firebase generates them. It comes from the library directly.

Look at the class: com.vitorpamplona.amethyst.service.notifications.PushNotificationReceiverService in the `play` flavor.

**Comment by KotlinGeekDev** [comment]
> Firebase generates them. It comes from the library directly.
> 
> Look at the class: com.vitorpamplona.amethyst.service.notifications.PushNotificationReceiverService in the `play` flavor.

I see. Thanks.

**Comment by KotlinGeekDev** [comment]
@vitorpamplona The token generation was interesting to me because Ntfy allows receiving notifications through topics. However, if one topic were to be used for all Amethyst users, everyone would see the notifications of everyone else.
For Ntfy it would be easier, since we can create a token with the pubkey alone, or do some thing like 'pushmsgs- ' + '<pubkey>', and the token is used as topic.

**Comment by KotlinGeekDev** [comment]
@vitorpamplona it seems the current Heroku instance will need to be used, to install ntfy there. The official ntfy.sh service has a (current) limit of 250 notifications and a max of 20mb of attachments per day.

**Comment by vitorpamplona** [comment]
ouch! we do have in less than one hour these days :(

**Comment by KotlinGeekDev** [comment]
> ouch! we do have in less than one hour these days :(

Yeah. So we have to self-host all the way. I wonder if Heroku gives you install privileges on the instance(s) you use.

**Comment by KotlinGeekDev** [comment]
@vitorpamplona the official ntfy.sh instance does have a paid level, probably with these limits removed.

**Comment by vitorpamplona** [comment]
I was under the impression that ntfy was a mechanism to allow each user to pay their own push notification server so that the server is fully controlled by the user and not us. Was I wrong?

**Comment by KotlinGeekDev** [comment]
> I was under the impression that ntfy was a mechanism to allow each user to pay their own push notification server so that the server is fully controlled by the user and not us. Was I wrong?

I think that is possible as well. :+1:

**Comment by KotlinGeekDev** [comment]
@vitorpamplona I did some more digging, and it seems that even though the user can choose their preferred push service, we will need a way to 'push' to the service, and that includes knowing the service URL(such as https://ntfy.sh), and storing it.

**Comment by KotlinGeekDev** [comment]
@vitorpamplona it seems we might have to alter the DB to include the Ntfy provider URL.(Or create another table identical to subscriptions, with the difference being the addition of the Ntfy provider URL)
