### ISSUE TITLE
Duplicate tokens for the same pubkey

### ISSUE THREAD

**Issue by KotlinGeekDev** [vitorpamplona/amethyst-push-notif-server#3]
I remarked this while testing, but forgot to address it. :sweat_smile:   When a certain person using for example, ntfy changes their push server, a new push URL is sent, but the server stores it as a new entry rather than replacing the current one.

**Comment by vitorpamplona** [comment]
It has to as you might have two clients in two phones with different tokens :)

Both clients should receive notifications.

**Comment by KotlinGeekDev** [comment]
> It has to as you might have two clients in two phones with different tokens :)
> 
> Both clients should receive notifications.

So I guess it is a feature, then. :sweat_smile:
